### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /github)

### ISSUE THREAD

**Issue by DmitrijOkeanij** [seanmiddleditch/gha-publish-to-git#8]
I have this file
```
name: CI  
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make files  
      run: |
        mkdir updir
        cd ./updir
        echo "1234" > ./file2.txt
        echo "4565" > ./file3.txt
        cd ..
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: My/Repo
        branch: master
        github_token: '${{ secrets.GITHUB_TOKEN  }}'
        github_pat: '${{ secrets.GH_PAT }}'
        source_folder: updir
```
![image](https://user-images.githubusercontent.com/10674646/73139118-b4ff3280-407b-11ea-97d3-4bdbe48c3209.png)
